server.port: ${PORT}

eureka.instance.preferIpAddress: true # register IP rather than the server name
eureka.client:
  registerWithEureka: true
  fetchRegistry: true # pull down a local copy of the registry
  serviceUrl.defaultZone: ${SERVICE_REGISTRY_URI}

hystrix:
 threadpool.default.coreSize: "20"
 threadpool.default.maxQueueSize: "500000"
 threadpool.default.keepAliveTimeMinutes: "2"
 threadpool.default.queueSizeRejectionThreshold: "500000"
 command:
   default:
     fallback.isolation.semaphore.maxConcurrentRequests: "20"
     execution:
       timeout:
         enabled: "false"
       isolation:
         strategy: "THREAD"
         thread:
           timeoutInMilliseconds: "30000"